services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: solana_ai
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
      

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    env_file: .env
    #volumes:
    #  - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db-data: